Algoritmo "tabuada"

Var
   Numero, contador, resultado : inteiro


Inicio

      escreval("Programa para cálculo da tabuada")
      escreva("Digite o número que deseja fazer a taboada: ")
      leia(numero)
      
      contador <- 0
      
      para contador de 1 ate 10 faca
          resultado <- Numero * contador
          escreval(Numero," x ", contador," = ",resultado)
      fimpara

Fimalgoritmo