Algoritmo "Terceiro"

Var
       Peso, altura, imc : real
       idade : inteiro
       nome : caractere


Inicio
      escreva("Digite seu nome: ")
      leia(nome)
      escreva("Digite sua idade: ")
      leia(idade)
      escreva("Digite seu peso: ")
      leia(peso)
      escreva("Digite sua altura: ")
      leia(altura)
      imc <- (Peso/(altura*altura))
      escreval
      escreval(Nome, " seu Imc é: ", imc:4:2)
      escreval("Até a próxima")


Fimalgoritmo